### ISSUE TITLE
Readme Snapshots

### ISSUE THREAD

**Issue by sheveg** [sheveg/roboyVR#1]
![sceneoverview](https://cloud.githubusercontent.com/assets/10234845/21025492/f72657fc-bd88-11e6-912e-877ba72d782e.png)
![simulationscene-roboymanagerip](https://cloud.githubusercontent.com/assets/10234845/21025737/da6cda5e-bd89-11e6-8755-af5fbf4a748b.png)
![simulationscene-tagroboypart](https://cloud.githubusercontent.com/assets/10234845/21025736/da6bcb1e-bd89-11e6-820d-be7b42853697.png)
![vivescene-selectableobj](https://cloud.githubusercontent.com/assets/10234845/21025738/da6c4c06-bd89-11e6-883c-db8d20462f42.png)
![vivescene-selectortool](https://cloud.githubusercontent.com/assets/10234845/21025739/da714120-bd89-11e6-93ee-45949cf7dfc8.png)

**Comment by cicomaniac** [comment]
Looking nice ;D
